- name: Ensure UFW is installed
  apt:
    name: ufw
    state: present

- name: Allow SSH
  ufw:
    rule: allow
    port: ssh

- name: Allow HTTP
  ufw:
    rule: allow
    port: '80'

- name: Enable UFW
  ufw:
    state: enabled
